Added a struct to set a rectangle on a display
R2D2-2019/internal_communication pull request #16
Opened 2019-04-05 14:40 UTC by itzandroidtab

2019-04-05 20:18 UTC, LRstudentHU requested changes

2019-04-05 20:18 UTC, LRstudentHU commented on code/headers/packet_types.hpp
> +    struct display_rectangle_s {
Please prefix your frame with "frame_"

2019-04-05 20:18 UTC, LRstudentHU commented on code/headers/packet_types.hpp
> +        uint8_t width;
I know that extended frames currently aren't supported, but does a `uint8_t` make sense for the width/height, when you need a `uint16_t` for the position? If you need more than a byte of the position, you wouldn't be able to create a "frame" around the edges of the screen for example.

2019-04-05 20:18 UTC, LRstudentHU commented on code/headers/packet_types.hpp
> +     * https://github.com/R2D2-2019/R2D2-2019/wiki/Display
Currently, there is no input/output on your module page. Please describe how this frame is going to satisfy your module input

2019-04-05 22:10 UTC, itzandroidtab commented on code/headers/packet_types.hpp
> +        uint8_t width;
We need the uint16_t for the position since we have a screen that has a resolution above 255 in width and I think it should be okay since even if you can't fill fully fill the screen with this you can do it in multiple times. And this is probably gonna change when the extended frames are here.

And what do you mean with the ""frame" around the edges"?

2019-04-05 22:10 UTC, itzandroidtab commented on code/headers/packet_types.hpp
> +    struct display_rectangle_s {
added the prefix

2019-04-05 22:15 UTC, itzandroidtab commented on code/headers/packet_types.hpp
> +     * https://github.com/R2D2-2019/R2D2-2019/wiki/Display
Added a interface description to the wiki page

2019-04-06 06:56 UTC, LRstudentHU commented on code/headers/packet_types.hpp
> +        uint8_t width;
If that is an acceptabel limitation, you could add it as a comment.
I meant a rectangle that is the maximum size; e.g. from 0,0 to width,height with a thickness of 1 or 2. That would be a "frame" that touches all edges of the screen.

2019-04-06 11:31 UTC, itzandroidtab commented on code/headers/packet_types.hpp
> +        uint8_t width;
The rectangle I was thinking of is always filled with the color you specify so no thickness of the rectangle. The same as the VNC protocol: https://www.hep.phy.cam.ac.uk/vnc_docs/howitworks.html

2019-04-06 11:45 UTC, LRstudentHU commented on code/headers/packet_types.hpp
> +        uint8_t width;
Ah okay, that actually wasn't clear for me. Could this be renamed to filled rectangle?

2019-04-06 13:04 UTC, itzandroidtab commented on code/headers/packet_types.hpp
> +        uint8_t width;
Changed the name of the struct. The team decided that we will change the x and y to uint8_t and we will change the x, y, width and height to uint16_t after the extended frames are supported

2019-04-06 13:40 UTC, LRstudentHU approved these changes

2019-04-06 13:40 UTC, merged