Frame UI command
R2D2-2019/internal_communication pull request #27
Opened 2019-05-02 13:07 UTC by jasperdewinther

2019-05-03 09:30 UTC, LRstudentHU requested changes

2019-05-03 09:30 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        char parameters;
As discussed, `command` and `parameters` can be combined by serializing (Pickle is the standard here: https://docs.python.org/3.7/library/pickle.html) the wrapped frame.

2019-05-03 09:30 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_ui_command_s{
Add a space after `_s`

2019-05-03 12:10 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        char parameters;
Maybe a link to the module as well?

2019-05-08 05:32 UTC, LRstudentHU commented
You also need to add the frame helper and enum value, see the readme for details

2019-05-09 10:52 UTC, LRstudentHU approved these changes

2019-05-09 10:53 UTC, merged