Frame battery level
R2D2-2019/internal_communication pull request #28
Opened 2019-05-08 20:14 UTC by LRstudentHU

2019-05-08 23:07 UTC, itzandroidtab requested changes

2019-05-08 23:07 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +     * Power wiki: https://github.com/R2D2-2019/R2D2-2019/wiki/Power
Could you place the wiki link on the next line?

2019-05-08 23:07 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        // The voltage is multiplied by 1000 in this
Is it not better to move a part of this to the wiki page?

2019-05-08 23:07 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    }
You are misding a ; after the struct

2019-05-08 23:11 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    R2D2_INTERNAL_FRAME_HELPER(frame_battery_level, BATTERY_LEVEL)
The type is missing the _s

2019-05-09 10:55 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        // The voltage is multiplied by 1000 in this
I think it would be good to have this comment here, so someone working with the code can discover why this is without consulting the wiki.

2019-05-09 12:03 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +	      UI_COMMAND,
This part

2019-05-09 13:58 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +	      UI_COMMAND,
Nice, Github UI showed it was correct :-/, will fix

2019-05-09 14:19 UTC, itzandroidtab approved these changes

2019-05-09 14:19 UTC, itzandroidtab approved these changes

2019-05-09 19:07 UTC, merged