Rework of the current buffer implementation to a ringbuffer.
R2D2-2019/internal_communication pull request #29
Opened 2019-05-08 22:53 UTC by itzandroidtab

2019-05-09 19:11 UTC, LRstudentHU requested changes

2019-05-09 19:11 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
> +        #pragma pack(1)
We should more into the specifics of this; is there are performance tradeoff due to packing (e.g. extra shifts needed)? Would it fit into the NFC memory area without?

2019-05-09 19:11 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
> +                } else if (size <= 32 * 8) {
32 * 8 is 256, I suppose there is no overflows in this comparison right?
The else statement is not required in any case.

2019-05-09 19:11 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
>          struct _memory_manager_s {
Do we still need this type?

2019-05-09 19:46 UTC, itzandroidtab commented on code/headers/nfc_mem.hpp
> +        #pragma pack(1)
Without the pack it will take an extra byte as padding. I think the speed trade off will be acceptable for the amount of memory we save

2019-05-09 19:47 UTC, itzandroidtab commented on code/headers/nfc_mem.hpp
>          struct _memory_manager_s {
maybe a rename to _uid_memory_manager_s is better. We only use it for managing the uid data pointers to memory atm.

2019-05-09 20:40 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
> +        #pragma pack(1)
Does it compile without packing? Saving memory doesn't mean much when it's in the NFC memory segment

2019-05-09 22:16 UTC, itzandroidtab commented on code/headers/nfc_mem.hpp
> +        #pragma pack(1)
Without the pact() the size is to big to fit in the nfc area.

2019-05-10 07:24 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
>          struct _memory_manager_s {
Could this code be inlined instead?

2019-05-13 06:49 UTC, LRstudentHU approved these changes

2019-05-13 06:49 UTC, merged