Added a coordinate frame.
R2D2-2019/internal_communication pull request #30
Opened 2019-05-11 10:55 UTC by Official12345

Added a coordinate frame for use by location detector.

2019-05-12 09:06 UTC, itzandroidtab requested changes
Master needs to be pulled in this repo as well.

2019-05-12 09:06 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        // This variable describes if the latitude value is towards north or south and if the longitude value is towards east or west.
This comment is a bit on the long side

2019-05-12 09:06 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint8_t north_east;
So this is two directions in a single uint8_t? Maybe a name change to simething with the word direction in it is better.

2019-05-12 13:47 UTC, Official12345 commented on code/headers/frame_types.hpp
> +        uint8_t north_east;
This variable is used for 2 bools. One bool is for north or south and the other for east or west. So i can't think of a better name.

2019-05-13 06:59 UTC, PatrickDekker98 commented on code/headers/frame_types.hpp
> +        uint8_t north_east;
Consider:
```c++
bool north_south
bool east_west
```

2019-05-13 08:15 UTC, Official12345 commented on code/headers/frame_types.hpp
> +        uint8_t north_east;
We combined them in order to save space, but if it is fine to make it into 2 seperate bools, then i'll do that instead.

2019-05-15 11:13 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_coordinate_s {
Can you change the order of the variables to highest to lowest.

And add a 

```cpp
#pragma pack(1)
```

before the struct

2019-05-15 11:23 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_coordinate_s {
This removes the padding from the struct and saves at least 1 byte

2019-05-16 19:12 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_coordinate_s {
Please add R2D2_PACK_STRUCT instead of `#pragma pack(1)`, as that is the new standard

2019-05-17 08:42 UTC, JasperOosterbroek commented on code/headers/frame_types.hpp
> +    struct frame_coordinate_s {
Why should he change the order from highest to lowest size, does this improve performance? I think the way it is now grouped by latitude and longitude is better for readability

2019-05-17 08:52 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_coordinate_s {
with pragma pack(1) you want all the big variables at the top to prevent misalignment on larger types

2019-05-17 08:52 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_coordinate_s {
and this is the standard now.

2019-05-17 12:37 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint16_t longitude_thousandth_second;
Maybe it is a good idea to use the short form of latitude/longitude.

https://acronyms.thefreedictionary.com/Latitude%2FLongitude

2019-05-17 12:42 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint16_t longitude_thousandth_second;
Same with seconds/degrees/minutes

2019-05-17 12:47 UTC, Gian1080 commented on code/headers/frame_types.hpp
> +        uint16_t longitude_thousandth_second;
This makes it more clear for the end user, a long could also be a datatype which could cause confusion. Min is a protected keyword.

2019-05-17 19:51 UTC, LRstudentHU requested changes

2019-05-17 19:51 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        char north_south_hemisphere;
Why use a char instead of a bool?

2019-05-19 11:57 UTC, Official12345 commented on code/headers/frame_types.hpp
> +        char north_south_hemisphere;
Quite a lot of people told me it was more readable

2019-05-19 12:07 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        char north_south_hemisphere;
It should be a bool if you are using it as a bool. A char is for characters.

2019-05-19 12:12 UTC, Official12345 commented on code/headers/frame_types.hpp
> +        char north_south_hemisphere;
I've been told that it is way more clear if you use 's' for south for example

2019-05-19 14:21 UTC, LRstudentHU approved these changes

2019-05-19 15:27 UTC, itzandroidtab approved these changes

2019-05-19 17:34 UTC, merged