Added display character frame
R2D2-2019/internal_communication pull request #31
Opened 2019-05-11 11:29 UTC by JensBouman

Until the extended frames are supported, this frame will only process 1 character. Once the extended frame type is available, I will increase the character amount.

2019-05-12 09:12 UTC, itzandroidtab requested changes
This branch is not up to date with master

2019-05-12 09:12 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        // position of rectangle
A character is a rectangle?

2019-05-12 09:12 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_display_character_s {
Maybe the name should tell what font is being used

2019-05-12 09:17 UTC, LRstudentHU requested changes

2019-05-12 09:17 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        uint8_t character;
Use a `char'  for characters and `uint8_t` or `int8_t` for numbers.

2019-05-12 09:20 UTC, LRstudentHU commented
A sidenote: would a cursor-like API be more logical? Currently, you're required to send color and position information in every frame, which is quite inefficient. Maybe you could "request" a cursor and keep an array of cursors. A cursor would keep position, color and maybe some other settings. 

I don't know if this is a great idea or what the PO thinks; but I do think we can be more efficient.

2019-05-15 11:40 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +		uint8_t red;
can you please change the tab's to spaces?

2019-05-15 11:48 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        DISPLAY_CHARACTER,
You should rename this to something with a 8x8 in there

2019-05-15 11:50 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_cursor_s {
You are missing the R2D2_INTERNAL_FRAME_HELPER for some of these structs

2019-05-16 08:53 UTC, wds444 commented
Extended frames are now supported, if you want you can now increase the size of the packet.

2019-05-16 10:23 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        // position of rectangle
Fixed in fa4b66958b427418406bcc78d2285b4ce062f68e

2019-05-16 10:23 UTC, JensBouman commented on code/headers/frame_types.hpp
> +    struct frame_display_character_s {
Fixed in fc8a61abc3b4644a1ff9934d539ce7b45ebc216b

2019-05-16 10:24 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        uint8_t character;
Fixed in fa4b66958b427418406bcc78d2285b4ce062f68e

2019-05-16 10:29 UTC, JensBouman commented on code/headers/frame_types.hpp
> +		uint8_t red;
Fixed in 969fb23

2019-05-16 10:33 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        DISPLAY_CHARACTER,
Fixed in 9c66184

2019-05-16 10:35 UTC, JensBouman commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_cursor_s {
Fixed in 71832b7e4b306d7f3571e198bb112f4d9494285d

2019-05-16 10:39 UTC, JensBouman commented on code/headers/frame_types.hpp
> +		uint8_t red;
And in dc2b0b0

2019-05-16 13:31 UTC, JensBouman commented
Updated the array size to the maximum.

2019-05-16 17:44 UTC, LRstudentHU requested changes

2019-05-16 17:44 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        display_cursor cursor_id;
The python bus won't understand `display_cursor`. Either create an issue there that they should support this (preferred), or change it to a `uint8_t`.

2019-05-16 17:44 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        uint8_t amount_characters;
Isn't the characters array null terminated?

2019-05-16 17:44 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_s {
Now that a cursor based solution is available, is this still relevant?

2019-05-16 18:26 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        display_cursor cursor_id;
I think that for now, uint8_t will suffice. Commited in b717cf6.

2019-05-16 18:26 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        uint8_t amount_characters;
You are right. Fixed in b717cf6.

2019-05-16 18:26 UTC, JensBouman commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_s {
If a person wants to write a single character for any reason whatsoever, it's possible in 1 frame. Unless it is necessary to free space it would be pointless to delete it, in my opinion.

2019-05-16 18:29 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_s {
In that case, allow them to write a bunch of characters now it will fit in an extended frame

2019-05-16 18:30 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_cursor_s {
Please add R2D2_PACK_STRUCT (please look at master for examples)

2019-05-16 18:31 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        uint8_t amount_characters;
That isn't exactly what I meant; you can remove this member altogether because of the null terminator.

2019-05-17 07:27 UTC, LRstudentHU commented
@itzandroidtab this is the first candidate for the string optimisation

2019-05-17 07:49 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        uint8_t amount_characters;
Fixed in 7d267b5eaa30648c3a38de3163ce32da03359374

2019-05-17 08:24 UTC, JensBouman commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_s {
2bede84

2019-05-17 11:04 UTC, LRstudentHU approved these changes

2019-05-17 13:22 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +     *
Newlines

2019-05-17 13:23 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +
Newline

2019-05-17 13:24 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +     * Currently only the 8x8 font from hwlib is supported,
I don't think this comment is necessary anymore. The struct tells us this is a 8x8 font

2019-05-17 13:25 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
Can you add what location these cursors have? Direct pixel location or the font 8x8 location

2019-05-17 13:28 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
Agreed, fixed in 83f772e

2019-05-17 13:29 UTC, JensBouman commented on code/headers/frame_types.hpp
> +     * Currently only the 8x8 font from hwlib is supported,
Agreed, fixed in 83f772e

2019-05-17 13:29 UTC, JensBouman commented on code/headers/frame_types.hpp
> +     *
Fixed in 6c6237b

2019-05-17 13:29 UTC, itzandroidtab requested changes

2019-05-17 13:29 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_cursor_s {
I dont think this name is correct for this struct. It sounds like this will set a cursor for a 8x8 font.

2019-05-17 13:30 UTC, JensBouman commented on code/headers/frame_types.hpp
> +
Fixed in 83f772e

2019-05-17 13:35 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
The linked commit doesnt add any documentation.

2019-05-17 13:43 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
You are right, I hastily made the wrong comment to the wrong change, my bad. I will change it soon.

2019-05-17 13:59 UTC, JensBouman commented on code/headers/frame_types.hpp
> +    struct frame_display_8x8_character_cursor_s {
I changed it to "frame_display_8x8_character_via_cursor_s" in ce2ae41

2019-05-17 14:03 UTC, JensBouman commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
Added more documentation about the cursor_id in ce2ae41. If this isn't what you meant, please say so.

2019-05-17 14:36 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
I meant in hwlib when you write to the screen the location is not directly the pixel you write to. (At leasts when I used it). 

So when you wrote to (1, 0) it would write as the second character on the first line. Is this following that principle or can you write to (100, 100) and it will start at pixel (100, 100) and write it from there?

2019-05-17 16:13 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
As I read it, this is simply pixel position.

2019-05-17 16:42 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        uint8_t cursor_x;
Okay sure then it is probably just me.

2019-05-17 16:42 UTC, itzandroidtab approved these changes

2019-05-17 17:08 UTC, merged