Extended frames
R2D2-2019/internal_communication pull request #34
Opened 2019-05-13 15:19 UTC by itzandroidtab

Full support for frames up to 256 bytes.
Also implements a host of optimisations.

2019-05-13 19:19 UTC, itzandroidtab commented on code/headers/channel.hpp
> +// void __CAN1_Handler() {
This is to remove around 2k of flash memory usage. This handler might be used to switch to CAN1 from CAN0

2019-05-13 19:21 UTC, itzandroidtab commented on code/headers/comm.hpp
> +            if (can_bus::comm_module_register_s::count <= 1 && _local_accepts_frame(type)) {
This check beforehand is so we dont have to allocate memory if no module on the sam3x8e uses the frame

2019-05-13 21:58 UTC, LRstudentHU commented on code/headers/comm.hpp
> +            if (can_bus::comm_module_register_s::count <= 1 && _local_accepts_frame(type)) {
Since it is simply a protected function, the leading underscore should be removed.

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/can.hpp
> +        uint32_t _get_mailbox_accept_mask(const uint8_t index) {
Could we inline and remove this?

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/can.hpp
>              if ((id & CAN_MID_MIDE) == CAN_MID_MIDE) {
Do we still need this check? This really as never been an issue.

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/channel.hpp
> +        static uint32_t get_mask(){
Space after `()`

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/channel.hpp
> +        static void set_mask(const uint32_t mask){
Space after `()`

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/channel.hpp
> +                detail::_memory_manager_s::_clear_data_for_uid(can_frame.sequence_uid, can_frame.frame_type);
Do we still want to inline the _clear/_get/_set functions for uid's?

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/channel.hpp
> +            while ((trailing_zeros = __CLZ(status)) < 32) {
A comment that explains the bit counting/reversing/shifting here might make this code more clear.

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
> +        buffer_type<1, p1_buffers_count>    p1_buffers;
A comment that explains these buffers would help

2019-05-13 22:04 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
> +    constexpr _nfc_memory_area_s::queue_type &_get_tx_queue_for_channel() {
We can probably inline/remove this function

2019-05-14 07:24 UTC, itzandroidtab commented on code/headers/can.hpp
>              if ((id & CAN_MID_MIDE) == CAN_MID_MIDE) {
I have removed this and the other check from the _read_mailbox. Because the MRDY is already checked, the MMI is probably already cleared before we are in this function and we dont expect non extended frames on the bus

2019-05-14 12:14 UTC, florianhumblot requested changes

2019-05-14 12:14 UTC, florianhumblot commented on code/headers/base_comm.hpp
> +        >
Nitpick: indentation

2019-05-14 12:14 UTC, florianhumblot commented on code/headers/base_comm.hpp
> +        >
Nitpick: indentation

2019-05-14 12:14 UTC, florianhumblot commented on code/headers/comm.hpp
> +#define register
What's this? It doesn't seem to be used anywhere in the file.

2019-05-14 12:14 UTC, florianhumblot commented on code/headers/nfc_mem.hpp
> +    struct _memory_manager_s {
Aren't structs supposed to be POD's only?

2019-05-14 12:21 UTC, LRstudentHU commented on code/headers/comm.hpp
> +#define register
IN `sam3.h`, the `register` keyword is used. This will emit a warning on newer versions of C++, which in turn is interpreted as an error. So this define prevents errors when including.

2019-05-14 12:22 UTC, LRstudentHU commented on code/headers/nfc_mem.hpp
> +    struct _memory_manager_s {
Technically this isn't a POD, but agreed. We were actually already looking at completely removing this struct. If not, we will change it to a class.

2019-05-14 12:37 UTC, florianhumblot commented on code/headers/comm.hpp
> +#define register
Maybe add a comment to reflect that as it's quite confusing without the context :)

2019-05-14 12:38 UTC, florianhumblot commented on code/headers/nfc_mem.hpp
> +    struct _memory_manager_s {
IMO you should either change it (small change, just change `struct` to `class` and global replace the name to become `_c` instead of `_s`) or delete it before this gets merged as it clearly does violate the styleguide.

2019-05-14 13:56 UTC, itzandroidtab commented on code/headers/channel.hpp
> +                detail::_memory_manager_s::_clear_data_for_uid(can_frame.sequence_uid, can_frame.frame_type);
Yes

2019-05-14 15:56 UTC, LRstudentHU commented on code/headers/channel.hpp
> +                // remove pointer from active uid_indices
Could we reuse the result from the search above?

2019-05-14 16:58 UTC, LRstudentHU commented on code/headers/channel.hpp
> +            _uid_index * uid_index;
Maybe use =

2019-05-15 07:15 UTC, itzandroidtab commented on code/headers/channel.hpp
> +            _uid_index * uid_index;
changed it to 

```cpp
_uid_index *uid_index = nullptr;
```

2019-05-15 08:59 UTC, florianhumblot approved these changes

2019-05-15 13:55 UTC, LRstudentHU approved these changes
Ready to merge!

2019-05-15 14:34 UTC, itzandroidtab commented
Ran some last tests and everything works as intended:

[https://youtu.be/fj5ITbrXnpY](https://youtu.be/fj5ITbrXnpY)

2019-05-15 15:05 UTC, merged