changed variable names of frame_ui_command
R2D2-2019/internal_communication pull request #36
Opened 2019-05-15 20:16 UTC by Timvdijk

2019-05-15 20:52 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        char params;
the command was the command with parameters right? We only need the parameters now?

2019-05-15 21:00 UTC, Timvdijk commented on code/headers/frame_types.hpp
> +        char params;
yes. frame_type is the thing we wish to execute now, the params are the values of this frame type. e.g.:
of frame_type `frame_ui_command` the params would (now) be the values for frame_name, params and destination

2019-05-16 08:29 UTC, LRstudentHU requested changes

2019-05-16 08:29 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        char params;
In the first situation, the whole frame would be serialized into a str and send over. How will this serialization work when you are only sending the arguments? 
Also, `frame_name` could be a number, since the frame type is an enumeration

2019-05-16 10:04 UTC, jasperdewinther commented on code/headers/frame_types.hpp
> +        char params;
As discussed with Gerrit there will be more commands than just frames. We will not only use the frames(for very low level commands, directly sending it to the module), but there will also be commands added from a json file. These commands will need more work than just putting the frame on the CAN-bus. These json files will have commands like general move_to or group(for swarm) and then swarm management needs to calculate all frames that need to be sent. (e.g. get map, ask for navigation for a path and then send all frames required one by one)

Swarm management also said that using different command and parameters would be easier for them.

https://docs.google.com/document/d/1Os19hqnqh1QjiJVSL9kkHsbZJmAHYGIJk4a--wRPf0E/edit?usp=sharing

2019-05-17 07:50 UTC, LRstudentHU commented
@itzandroidtab we can poison this frame, now that that is merged

2019-05-17 09:40 UTC, LRstudentHU commented
I see the frame has already been poisoned in the other branch, so that is fine

2019-05-17 09:40 UTC, LRstudentHU approved these changes

2019-05-17 10:38 UTC, merged