Feature array optimisation
R2D2-2019/internal_communication pull request #53
Opened 2019-05-18 12:29 UTC by itzandroidtab

2019-05-18 13:23 UTC, LRstudentHU approved these changes

2019-05-18 13:23 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        R2D2_OPTIMISE_ARRAY(frame_raw_data_s, length, data)
While it technically be possible to enable the array and the string optimisation at the same time, we probably shouldn't allow that. Maybe a compile time check should prevent this situation?

2019-05-18 13:23 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    constexpr bool array_member_offset_v = array_member_offset<T>::offset;
String offset and member offset are basically the same thing; we can combine this into a single offset class that is specialized.

2019-05-18 13:23 UTC, LRstudentHU commented on code/headers/base_comm.hpp
> +        template<typename T>
Could the `get_string...` and `get_array...`  functions be combined to a single function `get_optimized_offset` and move the `if constexpr` checks to that function? That would reduce the amount of duplication.

2019-05-18 13:24 UTC, LRstudentHU requested changes
Didn't mean to approve

2019-05-18 14:58 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        R2D2_OPTIMISE_ARRAY(frame_raw_data_s, length, data)
It shouldn't compile with both of the optimizations enabled anymore 
https://github.com/R2D2-2019/internal_communication/pull/53/commits/59fe958dc525126c1a55cc1461f286671915020e

2019-05-18 15:07 UTC, LRstudentHU requested changes
We should add both optimisations to the readme, including a small piece of text about why and how.

2019-05-18 15:07 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        RAW_DATA,
The test frame should be removed, can we apply this optimisation somewhere yet?

2019-05-18 15:48 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        RAW_DATA,
we might be able to add this to the frame_external_s

2019-05-18 15:53 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        RAW_DATA,
Don't think so at the moment. Maybe the external frame but that is already handled in the send_external function.

2019-05-18 18:18 UTC, YouriMulder reviewed
Can't give a really in depth review. Because most things happening in the code I don't understand really well. 
I suppose you thought about why for instance the array_offset is a uint16_t and the length_offset uint8_t?

2019-05-18 18:18 UTC, YouriMulder commented on README.md
> +When you have a array in a `struct` you can make them more efficient. To do so we can apply one of the optimisations to the frame. Currently we have two optimisations:
This is only a minor grammar issue. 

'a array' should be 'an array'.

2019-05-18 18:18 UTC, YouriMulder commented on README.md
> +**Important notice!!** When using the string optimisation you have to null-terminate the string. Reading after the null-terminator is Undefined behaviour.
Why is Undefined capitalized?

2019-05-18 18:18 UTC, YouriMulder commented on README.md
> +When you have a array in your frame we can apply the `R2D2_OPTIMISE_ARRAY` macro in the `R2D2_INTERNAL_FRAME_HELPER` macro. We have to put 3 parameters in this macro
Forgot a point at the end of the sentence.

2019-05-18 18:18 UTC, YouriMulder commented on README.md
> +The first parameter is the name of the `struct` again. The second parameter is the name of the variable where the length is stored, the the third variable is the name of the array again.
double the
'the the third'
I suppose this should be 'the third'.

2019-05-18 18:18 UTC, YouriMulder commented on code/headers/base_comm.hpp
> +         * This functions calculates the length of the actual frame.
'This function' should be 'This function'
This is only one function so plural is not correct as far as I know.

2019-05-18 18:18 UTC, YouriMulder commented on code/headers/base_comm.hpp
> +                // The string has to be 0-terminated.
I would prefer if this comment is placed inside the details of the docstring instead of here.
This makes the code harder to read in my opinion.

2019-05-18 18:18 UTC, YouriMulder commented on code/headers/base_comm.hpp
> +            // get the size of the data to send
Unnecessary comment in my opinion.

2019-05-18 18:36 UTC, LRstudentHU commented
> Can't give a really in depth review. Because most things happening in the code I don't understand really well.
> I suppose you thought about why for instance the array_offset is a uint16_t and the length_offset uint8_t?

That is actually a relic of refactoring, good catch. They should both be `uint8_t`.

2019-05-19 08:13 UTC, florianhumblot approved these changes
Everything's looking good, I haven't seen anything weird, looks ready for a merge to me!

2019-05-19 08:25 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        RAW_DATA,
Before we wrap the original frame into the `external` frame, we could use `get_optimised_length()`. That would reduce the size of the wrapped frame and, in turn, the external frame. That could save a lot of buffers.

2019-05-19 08:53 UTC, LRstudentHU approved these changes

2019-05-19 08:59 UTC, merged