Feature command_id frame
R2D2-2019/internal_communication pull request #58
Opened 2019-05-20 10:55 UTC by JordyAlkema

2019-05-20 11:00 UTC, LRstudentHU requested changes

2019-05-20 11:00 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        COMMAND_ID
Missing comma

2019-05-20 11:00 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        uint32_t cmd_id;
Please use `command_id` for clarity

2019-05-20 11:00 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    R2D2_INTERNAL_FRAME_HELPER(
Please keep the ordering. The order of the frames here should be the same as the actual order

2019-05-20 11:03 UTC, JordyAlkema commented on code/headers/frame_types.hpp
> +        uint32_t cmd_id;
This was done because other frames already use the term 'cmd_id', so to keep consistency I used the same abbreviation.

2019-05-20 11:41 UTC, JordyAlkema commented on code/headers/frame_types.hpp
> +    R2D2_INTERNAL_FRAME_HELPER(
I don't see where I put the frame in the wrong order, could you point out where it is?

2019-05-20 15:56 UTC, LRstudentHU requested changes

2019-05-20 15:56 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +        uint32_t cmd_id;
`command_id` is more in line with other member names within this file, so that is preferred.

2019-05-22 08:15 UTC, LRstudentHU approved these changes

2019-05-22 08:34 UTC, merged