added the frame types for filled circle and hollow circle
R2D2-2019/internal_communication pull request #67
Opened 2019-05-23 12:06 UTC by lldiegon

Added the frames for writing a filled circle & a hollow circle to the display.

2019-05-23 12:35 UTC, LRstudentHU requested changes

2019-05-23 12:35 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_display_hollow_circle_s {
- Are you going to create a cursor and non-cursor version of each display frame? Currently a cursor is useless when drawing a circle.
 - Maybe a boolean "filled" would be more logical, as that is the only difference between these frames

2019-05-23 12:46 UTC, lldiegon commented on code/headers/frame_types.hpp
> +    struct frame_display_hollow_circle_s {
I'm not going to do anything with the cursor for drawing a circle. Adding a 'filled' boolean is a good idea, I will make the changes and then commit again. Thank you.

2019-05-23 14:29 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +     * extended frames are here the position and width/height
Extended frames currently supported

2019-05-23 14:30 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +     * extended frames are here the position and width/height
Maybe it is a good idea to update the display rectangle as well in a new pr

2019-05-23 14:32 UTC, itzandroidtab requested changes
See extended frame comment

2019-05-23 15:17 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    struct frame_display_hollow_circle_s {
Why not, actually? It seems a bit weird that there are two API's but some actions support on or the other, while others support both.

2019-05-28 09:28 UTC, lldiegon commented on code/headers/frame_types.hpp
> +    struct frame_display_hollow_circle_s {
Fair enough, I submitted a new commit.

2019-05-28 15:33 UTC, LRstudentHU approved these changes

2019-05-28 16:05 UTC, itzandroidtab approved these changes

2019-05-28 16:07 UTC, merged