Feature add rtttl frame
R2D2-2019/internal_communication pull request #69
Opened 2019-05-28 15:55 UTC by PatrickDekker98

an rtttl frame that sends an rtttl string was added :/

2019-05-28 22:11 UTC, itzandroidtab requested changes
As this is a string this can use the string optimatisation

2019-05-28 22:13 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        //the rtttl string to be send
This comment needs a space between // and the

2019-05-28 22:14 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    * this was not my idea either
This part doesnt add anything to the docs

2019-05-29 12:57 UTC, LRstudentHU commented
> 
> 
> As this is a string this can use the string optimatisation

This is actually required before merging. Please look at the characters frame from display for an example.

2019-05-30 09:00 UTC, LRstudentHU requested changes

2019-05-30 09:00 UTC, LRstudentHU commented on code/headers/frame_types.hpp
> +    * this was not my idea either
Yup, please remove it before merging

2019-05-30 11:46 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    };
Can you add a newline after your struct?

2019-05-30 11:46 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    * this was not my idea either
You still didnt remove the "this was not my idea either"

2019-06-03 08:38 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        )
This has 8 spaces

2019-06-03 10:57 UTC, PatrickDekker98 commented on code/headers/frame_types.hpp
> +        )
should be resolved

2019-06-03 10:58 UTC, PatrickDekker98 commented on code/headers/frame_types.hpp
> +    };
yes yes should be resolved

2019-06-03 19:33 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    * @brief This is a frame that will be send to the sound module.
The `@brief` and `@details` should be removed to conform the rest of the file

2019-06-04 09:23 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    */
This struct is missing a wiki link

2019-06-04 11:47 UTC, PatrickDekker98 commented on code/headers/frame_types.hpp
> +    */
should be resolved

2019-06-04 11:47 UTC, PatrickDekker98 commented on code/headers/frame_types.hpp
> +    * @brief This is a frame that will be send to the sound module.
should be resolved

2019-06-04 14:45 UTC, itzandroidtab approved these changes

2019-06-05 20:24 UTC, LRstudentHU approved these changes

2019-06-06 10:57 UTC, merged