Added more frames for manual control
R2D2-2019/internal_communication pull request #76
Opened 2019-06-17 11:58 UTC by JordyAlkema

2019-06-19 14:52 UTC, itzandroidtab requested changes

2019-06-19 14:52 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        bool dpad_up;
Can you make an enum for the dpad value's as you probably can't press all directions at the same time.

2019-06-19 14:52 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    /**
Do we need a frame with the status of every button/joystick value? The controller can transmit multiple other frames right?

2019-06-19 14:52 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        MANUAL_CONTROL_CONTROLLER_STATES,
You should remove the `STATE` after the frame names.

2019-06-20 13:14 UTC, JordyAlkema commented on code/headers/frame_types.hpp
> +        bool dpad_up;
It is actually possible to press multiple buttons on the dpad, as we just map other controllers to a virtual controller that has a dpad, meaning it is a possibility that we bind regular buttons to the dpad if a controller has no dpad and more then 8 regular buttons.

2019-06-20 13:18 UTC, JordyAlkema commented on code/headers/frame_types.hpp
> +    /**
This is used for the setup, so we can send the complete state of the controller, after that we will send only updates.

2019-06-20 13:23 UTC, JordyAlkema commented on code/headers/frame_types.hpp
> +        MANUAL_CONTROL_CONTROLLER_STATES,
The demo for the canbus uses the same naming convention, `BUTTON_STATE` and `ACTIVITY_LED_STATE`. So I assumed I should follow this convention (?)

2019-06-20 17:41 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +    /**
So this frame is not necessary as the other frames can be used instead. This will take a little more data to transmit in the beginning but this is only used once.

2019-06-20 17:42 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        MANUAL_CONTROL_CONTROLLER_STATES,
The other frames are without the `STATE` so you can follow that convention.

2019-06-20 17:46 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        bool dpad_up;
Oke then you should change all the dpad to a single `uint8_t` and do some bitshifting for every direction on the dpad. The same for the other buttons. They should be combined to a single `uint8_t` as a bool uses 1 byte and currently this will waste 10.5 byes.

2019-06-25 09:49 UTC, JasperOosterbroek commented on code/headers/frame_types.hpp
> +        bool dpad_up;
You make a very good point on effeciency however looking at being time efficient on the development side it might be smarter to allow this so that we can finish a product.

2019-06-25 11:31 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +        bool dpad_up;
I dont agree with you. This takes more work to implement as we need an extra frame to request and respond to. This eliminates the need for extra code.

2019-06-26 12:49 UTC, JordyAlkema commented on code/headers/frame_types.hpp
> +        MANUAL_CONTROL_CONTROLLER_STATES,
80ffe1b0fe12a705f99303c3e06759489bd6802a

2019-06-26 14:55 UTC, itzandroidtab approved these changes

2019-06-27 08:46 UTC, merged