Feature flame detection frames
R2D2-2019/internal_communication pull request #78
Opened 2019-06-26 13:55 UTC by Rsambeek

2019-06-26 14:05 UTC, itzandroidtab requested changes

2019-06-26 14:05 UTC, itzandroidtab commented on code/headers/frame_types.hpp
> +     *
Can you add a description of the frame and a link to the wiki about the frame?

2019-06-26 14:34 UTC, Rsambeek commented on code/headers/frame_types.hpp
> +     *
I added the description and the link

2019-06-27 09:02 UTC, itzandroidtab approved these changes
The struct isn't the same as the interface on the wiki. But this looks okay.

2019-06-27 10:06 UTC, merged